<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VRCLogAnalyzer.Core\VRCLogAnalyzer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="NLog.config" CopyToOutputDirectory="PreserveNewest" />
    <None Update="VRCLogAnalyzer.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
